[package]
name = "yaml-loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.142"
serde_yaml = "0.9.4"
solana-sdk = "1.11.5"
